const typography = {
  DEFAULT: {
    css: {
      '--tw-prose-body': 'rgb(var(--color-fg-secondary))',
      '--tw-prose-bold': 'rgb(var(--color-fg-primary))',
      '--tw-prose-bullets': null,
      '--tw-prose-captions': null,
      '--tw-prose-code': null,
      '--tw-prose-counters': null,
      '--tw-prose-headings': 'rgb(var(--color-fg-primary))',
      '--tw-prose-hr': null,
      '--tw-prose-lead': null,
      '--tw-prose-links': null,
      '--tw-prose-pre-bg': null,
      '--tw-prose-pre-code': null,
      '--tw-prose-quote-borders': null,
      '--tw-prose-quotes': null,
      '--tw-prose-td-borders': null,
      '--tw-prose-th-borders': null,
      '--tw-prose-invert-body': null,
      '--tw-prose-invert-bold': null,
      '--tw-prose-invert-bullets': null,
      '--tw-prose-invert-captions': null,
      '--tw-prose-invert-code': null,
      '--tw-prose-invert-counters': null,
      '--tw-prose-invert-headings': null,
      '--tw-prose-invert-hr': null,
      '--tw-prose-invert-lead': null,
      '--tw-prose-invert-links': null,
      '--tw-prose-invert-pre-bg': null,
      '--tw-prose-invert-pre-code': null,
      '--tw-prose-invert-quote-borders': null,
      '--tw-prose-invert-quotes': null,
      '--tw-prose-invert-td-borders': null,
      '--tw-prose-invert-th-borders': null,
    },
  },
};

export default typography;
